TRUNCATE TABLE
  public.ai_chat_messages,
  public.ai_chat_threads,
  public.applications,
  public.assessments,
  public.bgv_documents,
  public.candidate_notes,
  public.candidate_profiles,
  public.chat_messages,
  public.gd_scores,
  public.gd_groups,
  public.group_discussions,
  public.interviews,
  public.job_templates,
  public.jobs,
  public.negotiation_messages,
  public.notifications,
  public.offer_letters,
  public.offer_templates,
  public.prep_sessions,
  public.scheduled_messages,
  public.test_answers,
  public.test_violations,
  public.user_notification_preferences,
  public.users,
  public.companies
RESTART IDENTITY CASCADE;